export const initialUsers = [
  {
    id: 'user_1',
    name: 'Abhishek Hindi',
    username: 'abhishek_h',
    email: 'abhishek@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    level: 14,
    tier: 'Scholar',
    dp: 2840,
    streak: 7,
    lastActiveDate: new Date().toISOString(),
    wins: 59,
    losses: 29,
    totalBattles: 88,
    score: 540,
    weeklyChange: 38,
    questionsAuthored: 7,
    pendingReviewCount: 2,
    monthlyRank: 1,
    totalPlayers: 1204,
    onlineStatus: 'online',
    bio: 'Theoretical mechanics buff & differential equations specialist. Competing in Apex Division.',
    royaltiesEarned: 128,
    globalAccuracy: 61,
    mostPlayedDeck: 'Science',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString()
  },
  {
    id: 'user_2',
    name: 'Abram Mango',
    username: 'abram_m',
    email: 'abram@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    level: 12,
    tier: 'MASTER DUELIST',
    dp: 2780,
    streak: 5,
    lastActiveDate: new Date().toISOString(),
    wins: 54,
    losses: 28,
    totalBattles: 82,
    score: 415,
    subject: 'AP Physics',
    onlineStatus: 'online',
    relationshipTag: 'Rival',
    createdAt: new Date(Date.now() - 75 * 86400000).toISOString()
  },
  {
    id: 'user_3',
    name: 'Alfonso Lubin',
    username: 'alfonso_l',
    email: 'alfonso@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    level: 15,
    tier: 'MASTER DUELIST',
    dp: 2690,
    streak: 4,
    wins: 49,
    losses: 26,
    totalBattles: 75,
    score: 390,
    subject: 'AP Calculus',
    onlineStatus: 'online',
    relationshipTag: 'Guild',
    createdAt: new Date(Date.now() - 80 * 86400000).toISOString()
  },
  {
    id: 'user_4',
    name: 'Maren Gouse',
    username: 'maren_g',
    email: 'maren@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    level: 9,
    tier: 'VETERAN SCHOLAR',
    dp: 2420,
    streak: 3,
    wins: 38,
    losses: 22,
    totalBattles: 60,
    score: 340,
    subject: 'AP Biology',
    onlineStatus: 'online',
    relationshipTag: 'Co-author',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString()
  },
  {
    id: 'user_5',
    name: 'James C.',
    username: 'james_c',
    email: 'james@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    level: 14,
    tier: 'MASTER DUELIST',
    dp: 2610,
    streak: 6,
    wins: 45,
    losses: 25,
    totalBattles: 70,
    score: 380,
    subject: 'AP Physics',
    onlineStatus: 'online',
    relationshipTag: 'Rival',
    createdAt: new Date(Date.now() - 70 * 86400000).toISOString()
  },
  {
    id: 'user_6',
    name: 'Elena V.',
    username: 'elena_v',
    email: 'elena@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    level: 11,
    tier: 'VETERAN SCHOLAR',
    dp: 2390,
    streak: 2,
    wins: 32,
    losses: 20,
    totalBattles: 52,
    score: 310,
    subject: 'Chemical Equilibrium',
    onlineStatus: 'online',
    relationshipTag: 'Reviewer',
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString()
  },
  {
    id: 'user_7',
    name: 'Lucas Meyer',
    username: 'lucas_m',
    email: 'lucas@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    level: 13,
    tier: 'MASTER DUELIST',
    dp: 2540,
    streak: 5,
    wins: 42,
    losses: 24,
    totalBattles: 66,
    score: 365,
    subject: 'AP Chemistry',
    onlineStatus: 'offline',
    relationshipTag: 'Guild',
    createdAt: new Date(Date.now() - 65 * 86400000).toISOString()
  },
  {
    id: 'user_8',
    name: 'Nadia Okonjo',
    username: 'nadia_o',
    email: 'nadia@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    level: 16,
    tier: 'APEX MASTER',
    dp: 2810,
    streak: 9,
    wins: 62,
    losses: 18,
    totalBattles: 80,
    score: 485,
    subject: 'Genetics & Biotech',
    onlineStatus: 'online',
    relationshipTag: 'Rival',
    createdAt: new Date(Date.now() - 100 * 86400000).toISOString()
  },
  {
    id: 'user_9',
    name: 'Marcus Vance',
    username: 'marcus_v',
    email: 'marcus@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    level: 10,
    tier: 'ELITE CADET',
    dp: 2480,
    streak: 4,
    wins: 36,
    losses: 15,
    totalBattles: 51,
    score: 330,
    subject: 'Computer Science',
    onlineStatus: 'online',
    relationshipTag: 'Guild',
    difficulty: 'medium',
    personality: 'Algorithmic Solver',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString()
  },
  {
    id: 'user_10',
    name: 'Aria Sterling',
    username: 'aria_s',
    email: 'aria@kweshun.edu',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    level: 17,
    tier: 'GRANDMASTER CADET',
    dp: 2920,
    streak: 11,
    wins: 72,
    losses: 10,
    totalBattles: 82,
    score: 520,
    subject: 'Quantum Mechanics',
    onlineStatus: 'online',
    relationshipTag: 'Apex Rival',
    difficulty: 'hard',
    personality: 'Lightning Reflexes',
    createdAt: new Date(Date.now() - 110 * 86400000).toISOString()
  }
];

export const initialDecks = [
  {
    id: 'deck_1',
    title: 'AP Physics 1: Mechanics',
    subtitle: 'Kinematics, Energy & Newton\'s Laws',
    category: 'Science',
    subject: 'Science',
    description: 'Master vectors, conservative forces, orbital trajectories, and rotational dynamics.',
    progress: 62,
    mastery: 62,
    totalQuestions: 140,
    questionCount: 140,
    activeLearners: 420,
    icon: '⚡',
    color: '#8b5cf6',
    featured: true
  },
  {
    id: 'deck_2',
    title: 'AP Calculus AB & BC',
    subtitle: 'Limits, Derivatives & Integrals',
    category: 'Science',
    subject: 'Science',
    description: 'Continuous functions, series convergence, differential equations, and Riemann sums.',
    progress: 84,
    mastery: 84,
    totalQuestions: 195,
    questionCount: 195,
    activeLearners: 530,
    icon: '📐',
    color: '#00f59b',
    featured: true
  },
  {
    id: 'deck_3',
    title: 'AP Chemistry',
    subtitle: 'Chemical Reactions & Stoichiometry',
    category: 'Science',
    subject: 'Science',
    description: 'Thermodynamics, reaction kinetics, chemical equilibrium, and orbital hybridization.',
    progress: 41,
    mastery: 41,
    totalQuestions: 165,
    questionCount: 165,
    activeLearners: 310,
    icon: '🧪',
    color: '#ef4444',
    featured: true
  },
  {
    id: 'deck_4',
    title: 'Science & Molecular Biology',
    subtitle: 'Foundations of Modern Genetics & Physics',
    category: 'Science',
    subject: 'Science',
    description: 'Broad STEM fundamentals covering quantum models, thermodynamics, and genetics.',
    progress: 75,
    mastery: 75,
    totalQuestions: 320,
    questionCount: 320,
    activeLearners: 890,
    icon: '🧬',
    color: '#06b6d4'
  },
  {
    id: 'deck_5',
    title: 'History & Geopolitics',
    subtitle: 'World Revolutions & Modern Diplomacy',
    category: 'History',
    subject: 'History',
    description: 'Decisive military campaigns, treaties, economic collapses, and political theory.',
    progress: 58,
    mastery: 58,
    totalQuestions: 210,
    questionCount: 210,
    activeLearners: 410,
    icon: '🏛️',
    color: '#f59e0b'
  },
  {
    id: 'deck_6',
    title: 'Pop Culture & Computing Lore',
    subtitle: 'Cinematic Lore & Gaming Milestones',
    category: 'Pop Culture',
    subject: 'Pop Culture',
    description: 'Sci-fi universes, game design milestones, iconic cinema, and music theory.',
    progress: 90,
    mastery: 90,
    totalQuestions: 180,
    questionCount: 180,
    activeLearners: 670,
    icon: '🎮',
    color: '#ec4899'
  },
  {
    id: 'deck_7',
    title: 'Art Movements & Architecture',
    subtitle: 'Renaissance to Contemporary Movements',
    category: 'Art',
    subject: 'Art',
    description: 'Chiaroscuro, Bauhaus architecture, color theory, and post-modern expressions.',
    progress: 50,
    mastery: 50,
    totalQuestions: 120,
    questionCount: 120,
    activeLearners: 290,
    icon: '🎨',
    color: '#a855f7'
  }
];

export const initialQuestions = [
  // -------------------------------------------------------------
  // DECK 1: AP Physics 1: Mechanics
  // -------------------------------------------------------------
  {
    id: 'Q-1001',
    authorId: 'user_1',
    deckId: 'deck_1',
    deckName: 'AP Physics 1: Mechanics',
    category: 'Science',
    topic: 'Rotational Inertia & Conservation',
    text: 'A solid cylinder and a thin hollow hoop of equal mass and radius roll down an incline from rest without slipping. Which reaches the bottom first, and why?',
    prompt: 'A solid cylinder and a thin hollow hoop of equal mass and radius roll down an incline from rest without slipping. Which reaches the bottom first, and why?',
    options: [
      { id: 'opt_1', text: 'The solid cylinder, because it has a lower moment of inertia (I = 1/2 MR² vs I = MR²).', isCorrect: true },
      { id: 'opt_2', text: 'The hollow hoop, because its mass is concentrated on the outer rim providing more linear torque.', isCorrect: false },
      { id: 'opt_3', text: 'They reach the bottom simultaneously because gravitational acceleration is independent of mass.', isCorrect: false },
      { id: 'opt_4', text: 'The solid cylinder, but only if the incline angle is greater than 45 degrees.', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'A smaller moment of inertia means less potential energy is converted into rotational kinetic energy, leaving more for translational velocity.',
    citation: 'Halliday & Resnick, Fundamentals of Physics 11th Ed., Ch. 11',
    citations: 'Halliday & Resnick, Fundamentals of Physics 11th Ed., Ch. 11',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 94, factualVerification: 96, difficultyBalance: 90, answerDistinction: 92, sourceCitations: 95, composite: 93, grade: 'A' },
    plays: 342,
    correctAttempts: 218,
    incorrectAttempts: 124,
    accuracy: 64,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString()
  },
  {
    id: 'Q-1002',
    authorId: 'user_2',
    deckId: 'deck_1',
    deckName: 'AP Physics 1: Mechanics',
    category: 'Science',
    topic: 'Relativistic Momentum',
    text: 'As an object\'s speed approaches the speed of light c in a vacuum, what happens to its relativistic momentum p?',
    prompt: 'As an object\'s speed approaches the speed of light c in a vacuum, what happens to its relativistic momentum p?',
    options: [
      { id: 'opt_1', text: 'It plateaus at exactly m₀c.', isCorrect: false },
      { id: 'opt_2', text: 'It approaches infinity due to the Lorentz factor γ = 1/√(1 - v²/c²).', isCorrect: true },
      { id: 'opt_3', text: 'It becomes zero as time dilates completely.', isCorrect: false },
      { id: 'opt_4', text: 'It increases purely linearly with velocity v.', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'Relativistic momentum p = γ m₀ v = (1 / √(1 - v²/c²)) m₀ v, which asymptotically approaches infinity as v -> c.',
    citation: 'Einstein, Special Relativity (1905)',
    citations: 'Einstein, Special Relativity (1905)',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 95, factualVerification: 97, difficultyBalance: 91, answerDistinction: 94, sourceCitations: 96, composite: 95, grade: 'A+' },
    plays: 680,
    correctAttempts: 410,
    incorrectAttempts: 270,
    accuracy: 60,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString()
  },
  {
    id: 'Q-1003',
    authorId: 'user_5',
    deckId: 'deck_1',
    deckName: 'AP Physics 1: Mechanics',
    category: 'Science',
    topic: 'Conservation of Angular Momentum',
    text: 'A figure skater spinning with outstretched arms pulls their arms tightly inward. What happens to their rotational kinetic energy?',
    prompt: 'A figure skater spinning with outstretched arms pulls their arms tightly inward. What happens to their rotational kinetic energy?',
    options: [
      { id: 'opt_1', text: 'It decreases because moment of inertia decreases.', isCorrect: false },
      { id: 'opt_2', text: 'It remains strictly constant due to energy conservation.', isCorrect: false },
      { id: 'opt_3', text: 'It increases because the skater does internal mechanical work pulling their arms inward.', isCorrect: true },
      { id: 'opt_4', text: 'It drops to zero momentarily.', isCorrect: false }
    ],
    correctAnswerIndex: 2,
    correctIndex: 2,
    explanation: 'Angular momentum L = Iω is conserved, so ω increases as I decreases. K_rot = L²/(2I); since I decreases, K_rot increases due to the positive work done by the muscles.',
    citation: 'Knight, Physics for Scientists and Engineers, Ch. 12',
    citations: 'Knight, Physics for Scientists and Engineers, Ch. 12',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 91, factualVerification: 95, difficultyBalance: 88, answerDistinction: 90, sourceCitations: 92, composite: 91, grade: 'A' },
    plays: 290,
    correctAttempts: 185,
    incorrectAttempts: 105,
    accuracy: 64,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString()
  },
  {
    id: 'Q-1004',
    authorId: 'user_1',
    deckId: 'deck_1',
    deckName: 'AP Physics 1: Mechanics',
    category: 'Science',
    topic: 'Simple Harmonic Motion',
    text: 'If the amplitude of a simple mass-spring harmonic oscillator is doubled, what happens to its total mechanical energy and period T?',
    prompt: 'If the amplitude of a simple mass-spring harmonic oscillator is doubled, what happens to its total mechanical energy and period T?',
    options: [
      { id: 'opt_1', text: 'Energy quadruples, and period T remains unchanged.', isCorrect: true },
      { id: 'opt_2', text: 'Energy doubles, and period T doubles.', isCorrect: false },
      { id: 'opt_3', text: 'Energy quadruples, and period T is halved.', isCorrect: false },
      { id: 'opt_4', text: 'Energy remains constant, and period T quadruples.', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Total energy E = 1/2 k A² scales with amplitude squared (2² = 4x). Period T = 2π√(m/k) is independent of amplitude in SHM.',
    citation: 'Tipler & Mosca, Physics for Scientists and Engineers 6th Ed., Ch. 14',
    citations: 'Tipler & Mosca, Physics for Scientists and Engineers 6th Ed., Ch. 14',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 88, factualVerification: 94, difficultyBalance: 86, answerDistinction: 89, sourceCitations: 90, composite: 89, grade: 'A-' },
    plays: 410,
    correctAttempts: 290,
    incorrectAttempts: 120,
    accuracy: 71,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString()
  },
  {
    id: 'Q-1005',
    authorId: 'user_2',
    deckId: 'deck_1',
    deckName: 'AP Physics 1: Mechanics',
    category: 'Science',
    topic: 'Fluid Dynamics & Bernoulli Principle',
    text: 'In an ideal horizontal fluid pipe with a constriction (venturi), what happens to the fluid velocity and pressure in the narrow section?',
    prompt: 'In an ideal horizontal fluid pipe with a constriction (venturi), what happens to the fluid velocity and pressure in the narrow section?',
    options: [
      { id: 'opt_1', text: 'Velocity decreases and pressure decreases.', isCorrect: false },
      { id: 'opt_2', text: 'Velocity increases and static pressure decreases.', isCorrect: true },
      { id: 'opt_3', text: 'Velocity increases and static pressure increases.', isCorrect: false },
      { id: 'opt_4', text: 'Both velocity and static pressure remain strictly constant.', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'By the continuity equation A1*v1 = A2*v2, velocity increases where area narrows. By Bernoulli\'s equation P + 1/2 ρ v² = const, higher velocity requires lower static pressure.',
    citation: 'Halliday & Resnick, Principles of Physics, Ch. 14 Fluid Mechanics',
    citations: 'Halliday & Resnick, Principles of Physics, Ch. 14 Fluid Mechanics',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 89, factualVerification: 96, difficultyBalance: 87, answerDistinction: 91, sourceCitations: 92, composite: 91, grade: 'A' },
    plays: 520,
    correctAttempts: 395,
    incorrectAttempts: 125,
    accuracy: 76,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString()
  },

  // -------------------------------------------------------------
  // DECK 2: AP Calculus AB & BC
  // -------------------------------------------------------------
  {
    id: 'Q-2001',
    authorId: 'user_1',
    deckId: 'deck_2',
    deckName: 'AP Calculus AB & BC',
    category: 'Science',
    topic: 'Fundamental Theorem of Calculus',
    text: 'If g(x) = ∫[from 2 to x³] cos(t²) dt, what is the exact derivative g\'(x)?',
    prompt: 'If g(x) = ∫[from 2 to x³] cos(t²) dt, what is the exact derivative g\'(x)?',
    options: [
      { id: 'opt_1', text: 'cos(x⁶) - cos(4)', isCorrect: false },
      { id: 'opt_2', text: '3x² · cos(x⁶)', isCorrect: true },
      { id: 'opt_3', text: '3x² · cos(x²)', isCorrect: false },
      { id: 'opt_4', text: '-2x · sin(x⁶)', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'By Leibniz rule and chain rule: d/dx ∫[a to u(x)] f(t) dt = f(u(x)) · u\'(x) = cos((x³)²) · 3x² = 3x² cos(x⁶).',
    citation: 'Stewart Calculus Early Transcendentals 8th Ed., Sec 5.3',
    citations: 'Stewart Calculus Early Transcendentals 8th Ed., Sec 5.3',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 90, factualVerification: 95, difficultyBalance: 88, answerDistinction: 91, sourceCitations: 90, composite: 91, grade: 'A' },
    plays: 512,
    correctAttempts: 348,
    incorrectAttempts: 164,
    accuracy: 68,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString()
  },
  {
    id: 'Q-2002',
    authorId: 'user_3',
    deckId: 'deck_2',
    deckName: 'AP Calculus AB & BC',
    category: 'Science',
    topic: 'Taylor & Maclaurin Series',
    text: 'What is the Maclaurin series expansion for the function f(x) = e^(2x)?',
    prompt: 'What is the Maclaurin series expansion for the function f(x) = e^(2x)?',
    options: [
      { id: 'opt_1', text: '∑[n=0 to ∞] (2x)ⁿ / n!', isCorrect: true },
      { id: 'opt_2', text: '∑[n=0 to ∞] 2 · xⁿ / n!', isCorrect: false },
      { id: 'opt_3', text: '∑[n=1 to ∞] (2x)ⁿ / (n+1)!', isCorrect: false },
      { id: 'opt_4', text: '∑[n=0 to ∞] (-1)ⁿ (2x)²ⁿ / (2n)!', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Since e^u = ∑ uⁿ / n!, replacing u with 2x gives ∑ (2x)ⁿ / n! = ∑ (2ⁿ xⁿ) / n! for all real x.',
    citation: 'Stewart Calculus, Chapter 11.10',
    citations: 'Stewart Calculus, Chapter 11.10',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 91, factualVerification: 96, difficultyBalance: 89, answerDistinction: 90, sourceCitations: 92, composite: 92, grade: 'A' },
    plays: 590,
    correctAttempts: 430,
    incorrectAttempts: 160,
    accuracy: 73,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString()
  },
  {
    id: 'Q-2003',
    authorId: 'user_3',
    deckId: 'deck_2',
    deckName: 'AP Calculus AB & BC',
    category: 'Science',
    topic: 'L\'Hôpital\'s Rule & Indeterminate Forms',
    text: 'Evaluate the limit: lim (x -> 0) [sin(5x) / (3x + tan(2x))].',
    prompt: 'Evaluate the limit: lim (x -> 0) [sin(5x) / (3x + tan(2x))].',
    options: [
      { id: 'opt_1', text: '5/3', isCorrect: false },
      { id: 'opt_2', text: '0', isCorrect: false },
      { id: 'opt_3', text: '1', isCorrect: true },
      { id: 'opt_4', text: '5/2', isCorrect: false }
    ],
    correctAnswerIndex: 2,
    correctIndex: 2,
    explanation: 'Plugging in x=0 gives 0/0. Applying L\'Hôpital\'s: d/dx[sin(5x)] = 5cos(5x); d/dx[3x + tan(2x)] = 3 + 2sec²(2x). At x=0: 5(1) / (3 + 2(1)) = 5/5 = 1.',
    citation: 'AP Calculus BC Course & Exam Description, Unit 4',
    citations: 'AP Calculus BC Course & Exam Description, Unit 4',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 92, factualVerification: 97, difficultyBalance: 89, answerDistinction: 93, sourceCitations: 91, composite: 92, grade: 'A' },
    plays: 380,
    correctAttempts: 260,
    incorrectAttempts: 120,
    accuracy: 68,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString()
  },
  {
    id: 'Q-2004',
    authorId: 'user_1',
    deckId: 'deck_2',
    deckName: 'AP Calculus AB & BC',
    category: 'Science',
    topic: 'Integration by Parts',
    text: 'What is the antiderivative of ∫ x · e^(3x) dx?',
    prompt: 'What is the antiderivative of ∫ x · e^(3x) dx?',
    options: [
      { id: 'opt_1', text: '(1/3) x e^(3x) - (1/9) e^(3x) + C', isCorrect: true },
      { id: 'opt_2', text: '(1/3) x e^(3x) + (1/3) e^(3x) + C', isCorrect: false },
      { id: 'opt_3', text: '(1/2) x² e^(3x) + C', isCorrect: false },
      { id: 'opt_4', text: '(1/9) x e^(3x) - (1/3) e^(3x) + C', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Let u = x, dv = e^(3x) dx -> du = dx, v = (1/3) e^(3x). ∫ u dv = uv - ∫ v du = (1/3) x e^(3x) - ∫ (1/3) e^(3x) dx = (1/3) x e^(3x) - (1/9) e^(3x) + C.',
    citation: 'Larson Calculus 11th Ed., Sec 8.2',
    citations: 'Larson Calculus 11th Ed., Sec 8.2',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 89, factualVerification: 98, difficultyBalance: 88, answerDistinction: 92, sourceCitations: 90, composite: 91, grade: 'A' },
    plays: 440,
    correctAttempts: 310,
    incorrectAttempts: 130,
    accuracy: 70,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString()
  },
  {
    id: 'Q-2005',
    authorId: 'user_3',
    deckId: 'deck_2',
    deckName: 'AP Calculus AB & BC',
    category: 'Science',
    topic: 'Series Convergence Tests',
    text: 'For what values of p does the infinite p-series ∑[n=1 to ∞] (1 / n^p) converge?',
    prompt: 'For what values of p does the infinite p-series ∑[n=1 to ∞] (1 / n^p) converge?',
    options: [
      { id: 'opt_1', text: 'p >= 1', isCorrect: false },
      { id: 'opt_2', text: 'p > 0', isCorrect: false },
      { id: 'opt_3', text: 'p > 1', isCorrect: true },
      { id: 'opt_4', text: 'p <= 1', isCorrect: false }
    ],
    correctAnswerIndex: 2,
    correctIndex: 2,
    explanation: 'By the integral test: ∫[1 to ∞] (1/x^p) dx converges strictly if and only if p > 1. At p = 1, it is the harmonic series which diverges.',
    citation: 'Stewart Calculus Early Transcendentals, Sec 11.3',
    citations: 'Stewart Calculus Early Transcendentals, Sec 11.3',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 87, factualVerification: 99, difficultyBalance: 85, answerDistinction: 94, sourceCitations: 93, composite: 91, grade: 'A' },
    plays: 620,
    correctAttempts: 495,
    incorrectAttempts: 125,
    accuracy: 80,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString()
  },

  // -------------------------------------------------------------
  // DECK 3: AP Chemistry
  // -------------------------------------------------------------
  {
    id: 'Q-3001',
    authorId: 'user_1',
    deckId: 'deck_3',
    deckName: 'AP Chemistry',
    category: 'Science',
    topic: 'Thermodynamic Spontaneity & Gibbs Energy',
    text: 'For an endothermic reaction where entropy increases (ΔH > 0, ΔS > 0), under what conditions is the reaction spontaneous?',
    prompt: 'For an endothermic reaction where entropy increases (ΔH > 0, ΔS > 0), under what conditions is the reaction spontaneous?',
    options: [
      { id: 'opt_1', text: 'Only at high temperatures where TΔS > ΔH', isCorrect: true },
      { id: 'opt_2', text: 'At all temperatures regardless of T', isCorrect: false },
      { id: 'opt_3', text: 'Only at low temperatures where ΔH dominates', isCorrect: false },
      { id: 'opt_4', text: 'Never spontaneous under standard pressure', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Since ΔG = ΔH - TΔS, when both ΔH and ΔS are positive, ΔG becomes negative (spontaneous) only when T is large enough that TΔS exceeds ΔH.',
    citation: 'AP Chemistry Curriculum Framework, Unit 9: Thermodynamics',
    citations: 'AP Chemistry Curriculum Framework, Unit 9: Thermodynamics',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 88, factualVerification: 92, difficultyBalance: 85, answerDistinction: 89, sourceCitations: 86, composite: 88, grade: 'A-' },
    plays: 289,
    correctAttempts: 173,
    incorrectAttempts: 116,
    accuracy: 60,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString()
  },
  {
    id: 'Q-3002',
    authorId: 'user_6',
    deckId: 'deck_3',
    deckName: 'AP Chemistry',
    category: 'Science',
    topic: 'Le Chatelier Principle',
    text: 'In the exothermic Haber process: N2(g) + 3H2(g) ⇌ 2NH3(g) (ΔH = -92 kJ/mol), what shift occurs if the container volume is decreased?',
    prompt: 'In the exothermic Haber process: N2(g) + 3H2(g) ⇌ 2NH3(g) (ΔH = -92 kJ/mol), what shift occurs if the container volume is decreased?',
    options: [
      { id: 'opt_1', text: 'Shifts toward reactants (left) to lower the total system pressure.', isCorrect: false },
      { id: 'opt_2', text: 'Shifts toward products (right), because 4 moles of gas compress to 2 moles.', isCorrect: true },
      { id: 'opt_3', text: 'No shift occurs because equilibrium constant Kp is invariant to volume.', isCorrect: false },
      { id: 'opt_4', text: 'The reaction stops completely.', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'Decreasing container volume increases total pressure. By Le Chatelier\'s principle, the system shifts toward the side with fewer gas molecules (2 moles NH3 vs 4 moles N2+3H2).',
    citation: 'Zumdahl Chemistry 10th Ed., Ch. 13 Chemical Equilibrium',
    citations: 'Zumdahl Chemistry 10th Ed., Ch. 13 Chemical Equilibrium',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 87, factualVerification: 95, difficultyBalance: 86, answerDistinction: 92, sourceCitations: 88, composite: 90, grade: 'A' },
    plays: 820,
    correctAttempts: 640,
    incorrectAttempts: 180,
    accuracy: 78,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString()
  },
  {
    id: 'Q-3003',
    authorId: 'user_7',
    deckId: 'deck_3',
    deckName: 'AP Chemistry',
    category: 'Science',
    topic: 'Buffer Capacity & Henderson-Hasselbalch',
    text: 'What is the pH of a buffer solution containing 0.20 M CH3COOH and 0.20 M CH3COONa (given Ka of acetic acid = 1.8 × 10⁻⁵, pKa = 4.74)?',
    prompt: 'What is the pH of a buffer solution containing 0.20 M CH3COOH and 0.20 M CH3COONa (given Ka of acetic acid = 1.8 × 10⁻⁵, pKa = 4.74)?',
    options: [
      { id: 'opt_1', text: 'pH = 4.74', isCorrect: true },
      { id: 'opt_2', text: 'pH = 7.00', isCorrect: false },
      { id: 'opt_3', text: 'pH = 5.04', isCorrect: false },
      { id: 'opt_4', text: 'pH = 3.84', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'By the Henderson-Hasselbalch equation: pH = pKa + log([A⁻]/[HA]). When [A⁻] = [HA] = 0.20 M, log(1) = 0, so pH = pKa = 4.74.',
    citation: 'Brown & LeMay, Chemistry: The Central Science 14th Ed., Ch. 17',
    citations: 'Brown & LeMay, Chemistry: The Central Science 14th Ed., Ch. 17',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 90, factualVerification: 98, difficultyBalance: 90, answerDistinction: 93, sourceCitations: 92, composite: 93, grade: 'A' },
    plays: 350,
    correctAttempts: 255,
    incorrectAttempts: 95,
    accuracy: 73,
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString()
  },
  {
    id: 'Q-3004',
    authorId: 'user_6',
    deckId: 'deck_3',
    deckName: 'AP Chemistry',
    category: 'Science',
    topic: 'Hybridization & Molecular Geometry',
    text: 'What is the hybridization and molecular geometry of sulfur tetrafluoride (SF4)?',
    prompt: 'What is the hybridization and molecular geometry of sulfur tetrafluoride (SF4)?',
    options: [
      { id: 'opt_1', text: 'sp³d hybridization, Seesaw geometry', isCorrect: true },
      { id: 'opt_2', text: 'sp³ hybridization, Tetrahedral geometry', isCorrect: false },
      { id: 'opt_3', text: 'sp³d² hybridization, Square planar geometry', isCorrect: false },
      { id: 'opt_4', text: 'sp² hybridization, Trigonal planar geometry', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'SF4 has 34 valence electrons: 4 bonding pairs + 1 lone pair on sulfur -> steric number 5 (sp³d hybridization with trigonal bipyramidal electron domain, resulting in Seesaw molecular geometry).',
    citation: 'VSEPR Theory Guidelines, AP Chemistry Unit 2',
    citations: 'VSEPR Theory Guidelines, AP Chemistry Unit 2',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 91, factualVerification: 97, difficultyBalance: 88, answerDistinction: 94, sourceCitations: 90, composite: 92, grade: 'A' },
    plays: 410,
    correctAttempts: 260,
    incorrectAttempts: 150,
    accuracy: 63,
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString()
  },
  {
    id: 'Q-3005',
    authorId: 'user_7',
    deckId: 'deck_3',
    deckName: 'AP Chemistry',
    category: 'Science',
    topic: 'Electrochemistry & Nernst Equation',
    text: 'What happens to the cell potential E_cell of a galvanic cell when the reaction reaches chemical equilibrium?',
    prompt: 'What happens to the cell potential E_cell of a galvanic cell when the reaction reaches chemical equilibrium?',
    options: [
      { id: 'opt_1', text: 'E_cell = E°_cell', isCorrect: false },
      { id: 'opt_2', text: 'E_cell reaches its maximum positive voltage.', isCorrect: false },
      { id: 'opt_3', text: 'E_cell = 0 V (the battery is completely dead).', isCorrect: true },
      { id: 'opt_4', text: 'E_cell becomes infinite.', isCorrect: false }
    ],
    correctAnswerIndex: 2,
    correctIndex: 2,
    explanation: 'At equilibrium, ΔG = 0. Since ΔG = -nFE_cell, E_cell must equal 0 V when the reaction reaches equilibrium (Q = K).',
    citation: 'AP Chemistry Unit 9: Electrochemistry & Thermodynamics',
    citations: 'AP Chemistry Unit 9: Electrochemistry & Thermodynamics',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 88, factualVerification: 96, difficultyBalance: 85, answerDistinction: 91, sourceCitations: 90, composite: 90, grade: 'A' },
    plays: 530,
    correctAttempts: 420,
    incorrectAttempts: 110,
    accuracy: 79,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString()
  },

  // -------------------------------------------------------------
  // DECK 4: Science & Molecular Biology
  // -------------------------------------------------------------
  {
    id: 'Q-4001',
    authorId: 'user_1',
    deckId: 'deck_4',
    deckName: 'Science & Molecular Biology',
    category: 'Science',
    topic: 'Photosynthesis & ATP Synthase',
    text: 'During non-cyclic photophosphorylation, what is the primary proton gradient generator that drives chloroplast ATP synthase?',
    prompt: 'During non-cyclic photophosphorylation, what is the primary proton gradient generator that drives chloroplast ATP synthase?',
    options: [
      { id: 'opt_1', text: 'Cytochrome b6f complex pumping H+ into the thylakoid lumen & photolysis of H2O', isCorrect: true },
      { id: 'opt_2', text: 'NADP+ reductase consuming protons exclusively in the stroma', isCorrect: false },
      { id: 'opt_3', text: 'Rubisco oxygenation pumping H+ across outer chloroplast membrane', isCorrect: false },
      { id: 'opt_4', text: 'Active transport of ATP molecules across the inner envelope', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Photolysis of water inside the thylakoid lumen plus the Q-cycle proton pumping by Cytochrome b6f creates the electrochemical proton gradient (ΔpH) that turns ATP synthase.',
    citation: 'Campbell Biology 12th Ed., Chapter 10: Photosynthesis',
    citations: 'Campbell Biology 12th Ed., Chapter 10: Photosynthesis',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 92, factualVerification: 94, difficultyBalance: 86, answerDistinction: 90, sourceCitations: 92, composite: 91, grade: 'A' },
    plays: 194,
    correctAttempts: 112,
    incorrectAttempts: 82,
    accuracy: 58,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString()
  },
  {
    id: 'Q-4002',
    authorId: 'user_4',
    deckId: 'deck_4',
    deckName: 'Science & Molecular Biology',
    category: 'Science',
    topic: 'CRISPR-Cas9 Mechanism',
    text: 'What specific sequence motif adjacent to the target DNA is strictly required for SpCas9 nuclease binding and double-strand cleavage?',
    prompt: 'What specific sequence motif adjacent to the target DNA is strictly required for SpCas9 nuclease binding and double-strand cleavage?',
    options: [
      { id: 'opt_1', text: 'TATA box promoter element', isCorrect: false },
      { id: 'opt_2', text: 'PAM sequence (Protospacer Adjacent Motif, typically 5\'-NGG-3\')', isCorrect: true },
      { id: 'opt_3', text: 'Poly-A tail sequence', isCorrect: false },
      { id: 'opt_4', text: 'Shine-Dalgarno ribosomal binding site', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'SpCas9 requires the PAM motif (NGG) immediately downstream of the 20-nucleotide target DNA sequence to initiate DNA unwinding and guide RNA pairing.',
    citation: 'Doudna & Charpentier, Science 2012; Nature Biotechnology Review 2020',
    citations: 'Doudna & Charpentier, Science 2012; Nature Biotechnology Review 2020',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 96, factualVerification: 98, difficultyBalance: 90, answerDistinction: 94, sourceCitations: 97, composite: 95, grade: 'A+' },
    plays: 410,
    correctAttempts: 250,
    incorrectAttempts: 160,
    accuracy: 61,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString()
  },
  {
    id: 'Q-4003',
    authorId: 'user_8',
    deckId: 'deck_4',
    deckName: 'Science & Molecular Biology',
    category: 'Science',
    topic: 'Quantum Mechanics & Wave-Particle Duality',
    text: 'According to the de Broglie hypothesis, what is the wavelength λ of a particle with mass m and velocity v?',
    prompt: 'According to the de Broglie hypothesis, what is the wavelength λ of a particle with mass m and velocity v?',
    options: [
      { id: 'opt_1', text: 'λ = h / (m · v)', isCorrect: true },
      { id: 'opt_2', text: 'λ = h · m · v', isCorrect: false },
      { id: 'opt_3', text: 'λ = (m · v) / h', isCorrect: false },
      { id: 'opt_4', text: 'λ = h / (m · c²)', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Louis de Broglie proposed that matter exhibits wave properties with wavelength λ = h / p = h / (m · v), where h is Planck\'s constant.',
    citation: 'Griffiths, Introduction to Quantum Mechanics 3rd Ed., Ch. 1',
    citations: 'Griffiths, Introduction to Quantum Mechanics 3rd Ed., Ch. 1',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 94, factualVerification: 99, difficultyBalance: 91, answerDistinction: 95, sourceCitations: 96, composite: 95, grade: 'A+' },
    plays: 580,
    correctAttempts: 410,
    incorrectAttempts: 170,
    accuracy: 71,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString()
  },
  {
    id: 'Q-4004',
    authorId: 'user_4',
    deckId: 'deck_4',
    deckName: 'Science & Molecular Biology',
    category: 'Science',
    topic: 'DNA Replication & Okazaki Fragments',
    text: 'Which enzyme is responsible for covalently linking Okazaki fragments together on the lagging strand during eukaryotic DNA replication?',
    prompt: 'Which enzyme is responsible for covalently linking Okazaki fragments together on the lagging strand during eukaryotic DNA replication?',
    options: [
      { id: 'opt_1', text: 'DNA Helicase', isCorrect: false },
      { id: 'opt_2', text: 'Topoisomerase II', isCorrect: false },
      { id: 'opt_3', text: 'DNA Ligase I', isCorrect: true },
      { id: 'opt_4', text: 'RNA Primase', isCorrect: false }
    ],
    correctAnswerIndex: 2,
    correctIndex: 2,
    explanation: 'DNA Ligase I catalyzes the formation of a phosphodiester bond between the 3\'-hydroxyl and 5\'-phosphate ends of adjacent Okazaki fragments.',
    citation: 'Lodish Molecular Cell Biology 8th Ed., Ch. 4',
    citations: 'Lodish Molecular Cell Biology 8th Ed., Ch. 4',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 89, factualVerification: 97, difficultyBalance: 87, answerDistinction: 92, sourceCitations: 91, composite: 91, grade: 'A' },
    plays: 640,
    correctAttempts: 510,
    incorrectAttempts: 130,
    accuracy: 80,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString()
  },
  {
    id: 'Q-4005',
    authorId: 'user_8',
    deckId: 'deck_4',
    deckName: 'Science & Molecular Biology',
    category: 'Science',
    topic: 'Plate Tectonics & Subduction Zones',
    text: 'At a convergent boundary between oceanic and continental lithosphere, which feature typically forms as the denser plate subducts?',
    prompt: 'At a convergent boundary between oceanic and continental lithosphere, which feature typically forms as the denser plate subducts?',
    options: [
      { id: 'opt_1', text: 'Mid-ocean spreading ridge', isCorrect: false },
      { id: 'opt_2', text: 'Deep-sea oceanic trench alongside a volcanic mountain arc', isCorrect: true },
      { id: 'opt_3', text: 'Transform strike-slip fault basin', isCorrect: false },
      { id: 'opt_4', text: 'Passive continental margin rift', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'The denser oceanic crust subducts beneath continental crust, carving a deep oceanic trench at the trench zone and feeding magma into a continental volcanic arc (e.g. the Andes).',
    citation: 'Tarbuck & Lutgens, Earth: An Introduction to Physical Geology 12th Ed.',
    citations: 'Tarbuck & Lutgens, Earth: An Introduction to Physical Geology 12th Ed.',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 90, factualVerification: 95, difficultyBalance: 88, answerDistinction: 90, sourceCitations: 91, composite: 91, grade: 'A' },
    plays: 310,
    correctAttempts: 230,
    incorrectAttempts: 80,
    accuracy: 74,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString()
  },

  // -------------------------------------------------------------
  // DECK 5: History & Geopolitics
  // -------------------------------------------------------------
  {
    id: 'Q-5001',
    authorId: 'user_1',
    deckId: 'deck_5',
    deckName: 'History & Geopolitics',
    category: 'History',
    topic: 'Congress of Vienna & Balance of Power',
    text: 'What was the primary geopolitical doctrine established by Klemens von Metternich at the Congress of Vienna (1814-1815)?',
    prompt: 'What was the primary geopolitical doctrine established by Klemens von Metternich at the Congress of Vienna (1814-1815)?',
    options: [
      { id: 'opt_1', text: 'The Concert of Europe and containment of revolutionary nationalism via balance of power', isCorrect: true },
      { id: 'opt_2', text: 'Unconditional military unification of the German Confederation under Prussia', isCorrect: false },
      { id: 'opt_3', text: 'Dissolution of the Ottoman Empire through the Holy Alliance pact', isCorrect: false },
      { id: 'opt_4', text: 'Establishment of the League of Armed Neutrality against Great Britain', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Metternich organized the Concert of Europe to maintain dynastic legitimacy, suppress revolutionary liberalism, and ensure no single continental power could dominate Europe.',
    citation: 'Kissinger, A World Restored: Metternich, Castlereagh and the Problems of Peace',
    citations: 'Kissinger, A World Restored: Metternich, Castlereagh and the Problems of Peace',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 89, factualVerification: 91, difficultyBalance: 84, answerDistinction: 88, sourceCitations: 88, composite: 88, grade: 'A-' },
    plays: 42,
    correctAttempts: 27,
    incorrectAttempts: 15,
    accuracy: 64,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString()
  },
  {
    id: 'Q-5002',
    authorId: 'user_5',
    deckId: 'deck_5',
    deckName: 'History & Geopolitics',
    category: 'History',
    topic: 'Treaty of Versailles (1919)',
    text: 'Which controversial clause in the 1919 Treaty of Versailles explicitly assigned sole legal responsibility for WWI to Germany and its allies?',
    prompt: 'Which controversial clause in the 1919 Treaty of Versailles explicitly assigned sole legal responsibility for WWI to Germany and its allies?',
    options: [
      { id: 'opt_1', text: 'Article 48 (Emergency Decrees Clause)', isCorrect: false },
      { id: 'opt_2', text: 'Article 231 (The War Guilt Clause)', isCorrect: true },
      { id: 'opt_3', text: 'Article 10 (Collective Security Covenant)', isCorrect: false },
      { id: 'opt_4', text: 'Article 119 (Colonial Renunciation Clause)', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'Article 231 of the Treaty of Versailles forced Germany to accept moral and financial responsibility for all loss and damage caused by the war.',
    citation: 'MacMillan, Paris 1919: Six Months That Changed the World',
    citations: 'MacMillan, Paris 1919: Six Months That Changed the World',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 90, factualVerification: 97, difficultyBalance: 89, answerDistinction: 93, sourceCitations: 94, composite: 93, grade: 'A' },
    plays: 380,
    correctAttempts: 290,
    incorrectAttempts: 90,
    accuracy: 76,
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString()
  },
  {
    id: 'Q-5003',
    authorId: 'user_1',
    deckId: 'deck_5',
    deckName: 'History & Geopolitics',
    category: 'History',
    topic: 'Magna Carta & Constitutional Law',
    text: 'Signed in 1215 at Runnymede, what fundamental legal principle was first codified in Clause 39 of the Magna Carta?',
    prompt: 'Signed in 1215 at Runnymede, what fundamental legal principle was first codified in Clause 39 of the Magna Carta?',
    options: [
      { id: 'opt_1', text: 'Universal adult suffrage and secret ballot voting', isCorrect: false },
      { id: 'opt_2', text: 'Absolute divine right of monarchical succession', isCorrect: false },
      { id: 'opt_3', text: 'Due process of law and protection against unlawful imprisonment', isCorrect: true },
      { id: 'opt_4', text: 'Abolition of all feudal tax levies across barons', isCorrect: false }
    ],
    correctAnswerIndex: 2,
    correctIndex: 2,
    explanation: 'Clause 39 established that no free man shall be seized, imprisoned, or stripped of rights except by lawful judgment of equals or the law of the land (due process).',
    citation: 'Holt, Magna Carta 3rd Ed., Cambridge University Press',
    citations: 'Holt, Magna Carta 3rd Ed., Cambridge University Press',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 92, factualVerification: 98, difficultyBalance: 90, answerDistinction: 94, sourceCitations: 95, composite: 94, grade: 'A' },
    plays: 260,
    correctAttempts: 195,
    incorrectAttempts: 65,
    accuracy: 75,
    createdAt: new Date(Date.now() - 17 * 86400000).toISOString()
  },
  {
    id: 'Q-5004',
    authorId: 'user_5',
    deckId: 'deck_5',
    deckName: 'History & Geopolitics',
    category: 'History',
    topic: 'The Silk Road & Eurasian Exchange',
    text: 'During the Pax Mongolica in the 13th and 14th centuries, what major economic system facilitated unprecedented trade security across Eurasia?',
    prompt: 'During the Pax Mongolica in the 13th and 14th centuries, what major economic system facilitated unprecedented trade security across Eurasia?',
    options: [
      { id: 'opt_1', text: 'The Yam postal relay network and Paiza passport system', isCorrect: true },
      { id: 'opt_2', text: 'The Hanseatic League maritime convoy fleet', isCorrect: false },
      { id: 'opt_3', text: 'The Venetian Ducat gold standard monopoly', isCorrect: false },
      { id: 'opt_4', text: 'The Ming Dynasty tributary voyage mandate', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'The Mongol Empire\'s Yam relay stations and Paiza metal tablet passports guaranteed safe passage and fast communications across China, Central Asia, and Eastern Europe.',
    citation: 'Frankopan, The Silk Roads: A New History of the World',
    citations: 'Frankopan, The Silk Roads: A New History of the World',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 94, factualVerification: 96, difficultyBalance: 88, answerDistinction: 92, sourceCitations: 93, composite: 93, grade: 'A' },
    plays: 190,
    correctAttempts: 120,
    incorrectAttempts: 70,
    accuracy: 63,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString()
  },
  {
    id: 'Q-5005',
    authorId: 'user_1',
    deckId: 'deck_5',
    deckName: 'History & Geopolitics',
    category: 'History',
    topic: 'Industrial Revolution & Energy Transitions',
    text: 'What was James Watt\'s crucial 1769 technical innovation that radically improved the efficiency of the Newcomen atmospheric steam engine?',
    prompt: 'What was James Watt\'s crucial 1769 technical innovation that radically improved the efficiency of the Newcomen atmospheric steam engine?',
    options: [
      { id: 'opt_1', text: 'The separate steam condenser chamber', isCorrect: true },
      { id: 'opt_2', text: 'The direct electrical ignition coil', isCorrect: false },
      { id: 'opt_3', text: 'The internal combustion four-stroke valve', isCorrect: false },
      { id: 'opt_4', text: 'The centrifugal oil turbine rotor', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Watt added a separate condenser chamber, avoiding the need to repeatedly cool and reheat the main cylinder, cutting fuel usage by more than 75%.',
    citation: 'Landes, The Unbound Prometheus: Technical Change 1750 to Present',
    citations: 'Landes, The Unbound Prometheus: Technical Change 1750 to Present',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 91, factualVerification: 97, difficultyBalance: 89, answerDistinction: 92, sourceCitations: 94, composite: 93, grade: 'A' },
    plays: 310,
    correctAttempts: 235,
    incorrectAttempts: 75,
    accuracy: 76,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString()
  },

  // -------------------------------------------------------------
  // DECK 6: Pop Culture & Computing Lore
  // -------------------------------------------------------------
  {
    id: 'Q-6001',
    authorId: 'user_1',
    deckId: 'deck_6',
    deckName: 'Pop Culture & Computing Lore',
    category: 'Pop Culture',
    topic: 'Game Design & Computational Complexity',
    text: 'In John Conway’s cellular automaton Game of Life, what specific repeating pattern of four oscillator states moves diagonally across the 2D grid?',
    prompt: 'In John Conway’s cellular automaton Game of Life, what specific repeating pattern of four oscillator states moves diagonally across the 2D grid?',
    options: [
      { id: 'opt_1', text: 'A Glider', isCorrect: true },
      { id: 'opt_2', text: 'A Pulsar', isCorrect: false },
      { id: 'opt_3', text: 'A Gosper Gun', isCorrect: false },
      { id: 'opt_4', text: 'A Lightweight Spaceship (LWSS)', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'The Glider is the smallest and most famous spaceship in Conway’s Game of Life, traveling diagonally 1 cell every 4 generations.',
    citation: 'Gardner, Martin. Mathematical Games: The Fantastic Combinations of John Conway\'s Game of Life',
    citations: 'Gardner, Martin. Mathematical Games: The Fantastic Combinations of John Conway\'s Game of Life',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 93, factualVerification: 94, difficultyBalance: 82, answerDistinction: 86, sourceCitations: 89, composite: 89, grade: 'A-' },
    plays: 18,
    correctAttempts: 13,
    incorrectAttempts: 5,
    accuracy: 72,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString()
  },
  {
    id: 'Q-6002',
    authorId: 'user_2',
    deckId: 'deck_6',
    deckName: 'Pop Culture & Computing Lore',
    category: 'Pop Culture',
    topic: 'The Turing Test & Imitation Game',
    text: 'In Alan Turing\'s foundational 1950 paper "Computing Machinery and Intelligence", what was the original name of the test he proposed?',
    prompt: 'In Alan Turing\'s foundational 1950 paper "Computing Machinery and Intelligence", what was the original name of the test he proposed?',
    options: [
      { id: 'opt_1', text: 'The Heuristic Probe', isCorrect: false },
      { id: 'opt_2', text: 'The Imitation Game', isCorrect: true },
      { id: 'opt_3', text: 'The Chinese Room Protocol', isCorrect: false },
      { id: 'opt_4', text: 'The Cybernetic Dialogue', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'Turing introduced the test under the title "The Imitation Game", asking whether an interrogator could distinguish text outputs of a machine from a human.',
    citation: 'Turing, A. M. (1950). Computing Machinery and Intelligence. Mind, 59(236), 433-460',
    citations: 'Turing, A. M. (1950). Computing Machinery and Intelligence. Mind, 59(236), 433-460',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 92, factualVerification: 99, difficultyBalance: 88, answerDistinction: 94, sourceCitations: 96, composite: 94, grade: 'A' },
    plays: 470,
    correctAttempts: 390,
    incorrectAttempts: 80,
    accuracy: 83,
    createdAt: new Date(Date.now() - 19 * 86400000).toISOString()
  },
  {
    id: 'Q-6003',
    authorId: 'user_4',
    deckId: 'deck_6',
    deckName: 'Pop Culture & Computing Lore',
    category: 'Pop Culture',
    topic: '8-Bit Sound Synthesis & Chiptune',
    text: 'Which iconic dedicated sound synthesizer chip provided the 3-channel audio and programmable envelope in the 1982 Commodore 64?',
    prompt: 'Which iconic dedicated sound synthesizer chip provided the 3-channel audio and programmable envelope in the 1982 Commodore 64?',
    options: [
      { id: 'opt_1', text: 'MOS Technology SID (6581 / 8580)', isCorrect: true },
      { id: 'opt_2', text: 'Yamaha YM2612 OPN2', isCorrect: false },
      { id: 'opt_3', text: 'Texas Instruments SN76489', isCorrect: false },
      { id: 'opt_4', text: 'Sony SPC700', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Designed by Bob Yannes, the MOS 6581 SID (Sound Interface Device) gave the Commodore 64 its rich analog synthesis and multi-waveform audio capabilities.',
    citation: 'Bagnall, Commodore: A Company on the Edge, Variant Press',
    citations: 'Bagnall, Commodore: A Company on the Edge, Variant Press',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 95, factualVerification: 98, difficultyBalance: 91, answerDistinction: 94, sourceCitations: 95, composite: 95, grade: 'A+' },
    plays: 210,
    correctAttempts: 135,
    incorrectAttempts: 75,
    accuracy: 64,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString()
  },
  {
    id: 'Q-6004',
    authorId: 'user_3',
    deckId: 'deck_6',
    deckName: 'Pop Culture & Computing Lore',
    category: 'Pop Culture',
    topic: 'Hard Sci-Fi Canon',
    text: 'In Isaac Asimov\'s Robot series, what is the First Law of Robotics?',
    prompt: 'In Isaac Asimov\'s Robot series, what is the First Law of Robotics?',
    options: [
      { id: 'opt_1', text: 'A robot must obey orders given it by human beings except where such orders conflict with the higher Laws.', isCorrect: false },
      { id: 'opt_2', text: 'A robot may not injure a human being or, through inaction, allow a human being to come to harm.', isCorrect: true },
      { id: 'opt_3', text: 'A robot must protect its own existence as long as such protection does not conflict with the First or Second Law.', isCorrect: false },
      { id: 'opt_4', text: 'A robot must prioritize planetary ecological equilibrium over individual survival.', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'The First Law: A robot may not injure a human being or, through inaction, allow a human being to come to harm (introduced in "Runaround", 1942).',
    citation: 'Asimov, Isaac. I, Robot, Gnome Press 1950',
    citations: 'Asimov, Isaac. I, Robot, Gnome Press 1950',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 88, factualVerification: 99, difficultyBalance: 86, answerDistinction: 95, sourceCitations: 93, composite: 92, grade: 'A' },
    plays: 680,
    correctAttempts: 590,
    incorrectAttempts: 90,
    accuracy: 87,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString()
  },
  {
    id: 'Q-6005',
    authorId: 'user_1',
    deckId: 'deck_6',
    deckName: 'Pop Culture & Computing Lore',
    category: 'Pop Culture',
    topic: 'Computer Graphics & Ray Tracing',
    text: 'Who formulated the fundamental Rendering Equation in 1986 that unified global illumination algorithms in computer graphics?',
    prompt: 'Who formulated the fundamental Rendering Equation in 1986 that unified global illumination algorithms in computer graphics?',
    options: [
      { id: 'opt_1', text: 'Jim Blinn', isCorrect: false },
      { id: 'opt_2', text: 'Bui Tuong Phong', isCorrect: false },
      { id: 'opt_3', text: 'James Kajiya', isCorrect: true },
      { id: 'opt_4', text: 'Ed Catmull', isCorrect: false }
    ],
    correctAnswerIndex: 2,
    correctIndex: 2,
    explanation: 'James Kajiya published "The Rendering Equation" at ACM SIGGRAPH 1986, establishing the integral equation governing radiative light transport in virtual scenes.',
    citation: 'Kajiya, J. T. (1986). The Rendering Equation. ACM SIGGRAPH Computer Graphics, 20(4), 143-150',
    citations: 'Kajiya, J. T. (1986). The Rendering Equation. ACM SIGGRAPH Computer Graphics, 20(4), 143-150',
    difficulty: 'hard',
    status: 'Live',
    qualityScores: { originality: 95, factualVerification: 98, difficultyBalance: 92, answerDistinction: 94, sourceCitations: 96, composite: 95, grade: 'A+' },
    plays: 160,
    correctAttempts: 95,
    incorrectAttempts: 65,
    accuracy: 59,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString()
  },

  // -------------------------------------------------------------
  // DECK 7: Art Movements & Architecture
  // -------------------------------------------------------------
  {
    id: 'Q-7001',
    authorId: 'user_1',
    deckId: 'deck_7',
    deckName: 'Art Movements & Architecture',
    category: 'Art',
    topic: 'Baroque Chiaroscuro & Caravaggism',
    text: 'Which extreme lighting technique, pioneered by Caravaggio, utilizes violent contrasts of impenetrable shadows and intense directional spotlights?',
    prompt: 'Which extreme lighting technique, pioneered by Caravaggio, utilizes violent contrasts of impenetrable shadows and intense directional spotlights?',
    options: [
      { id: 'opt_1', text: 'Tenebrism', isCorrect: true },
      { id: 'opt_2', text: 'Sfumato', isCorrect: false },
      { id: 'opt_3', text: 'Grisaille', isCorrect: false },
      { id: 'opt_4', text: 'Impasto', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Tenebrism (from Italian tenebroso, "dark, gloomy, mysterious") is a heightened form of chiaroscuro where darkness becomes a dominant, theatrical feature.',
    citation: 'Gardner\'s Art Through the Ages, Baroque Era Ch. 24',
    citations: 'Gardner\'s Art Through the Ages, Baroque Era Ch. 24',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 90, factualVerification: 96, difficultyBalance: 88, answerDistinction: 91, sourceCitations: 90, composite: 91, grade: 'A' },
    plays: 140,
    correctAttempts: 98,
    incorrectAttempts: 42,
    accuracy: 70,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString()
  },
  {
    id: 'Q-7002',
    authorId: 'user_4',
    deckId: 'deck_7',
    deckName: 'Art Movements & Architecture',
    category: 'Art',
    topic: 'Bauhaus Design Philosophy',
    text: 'Founded in Weimar in 1919 by Walter Gropius, which famous design principle became the cornerstone of the Bauhaus movement?',
    prompt: 'Founded in Weimar in 1919 by Walter Gropius, which famous design principle became the cornerstone of the Bauhaus movement?',
    options: [
      { id: 'opt_1', text: 'Ornament is Crime and Craftsmanship is Obsolete', isCorrect: false },
      { id: 'opt_2', text: 'Form follows function and the unification of art and industrial craft', isCorrect: true },
      { id: 'opt_3', text: 'Revival of Gothic romanticism and medieval guild exclusivity', isCorrect: false },
      { id: 'opt_4', text: 'Strict symmetry and classical column proportions', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'Bauhaus emphasized "form follows function", stripping away gratuitous ornament to integrate fine art with mass-manufactured industrial design.',
    citation: 'Whitford, Bauhaus (World of Art), Thames & Hudson',
    citations: 'Whitford, Bauhaus (World of Art), Thames & Hudson',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 91, factualVerification: 98, difficultyBalance: 89, answerDistinction: 93, sourceCitations: 94, composite: 93, grade: 'A' },
    plays: 320,
    correctAttempts: 255,
    incorrectAttempts: 65,
    accuracy: 80,
    createdAt: new Date(Date.now() - 16 * 86400000).toISOString()
  },
  {
    id: 'Q-7003',
    authorId: 'user_7',
    deckId: 'deck_7',
    deckName: 'Art Movements & Architecture',
    category: 'Art',
    topic: 'Gothic Architecture & Structural Engineering',
    text: 'Which architectural innovation enabled Gothic cathedrals like Chartres to construct soaring, thin walls filled with stained glass?',
    prompt: 'Which architectural innovation enabled Gothic cathedrals like Chartres to construct soaring, thin walls filled with stained glass?',
    options: [
      { id: 'opt_1', text: 'Massive Romanesque barrel vaults and solid load-bearing pillars', isCorrect: false },
      { id: 'opt_2', text: 'Flying buttresses combined with pointed arches and ribbed groin vaults', isCorrect: true },
      { id: 'opt_3', text: 'Corbelled dome pendentives supported by squinches', isCorrect: false },
      { id: 'opt_4', text: 'Post-and-lintel marble trabeation', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'Flying buttresses transmitted the lateral thrust of heavy roof vaults outward away from the walls, permitting high clerestories and massive stained glass windows.',
    citation: 'Bony, French Gothic Architecture of the 12th and 13th Centuries, UC Press',
    citations: 'Bony, French Gothic Architecture of the 12th and 13th Centuries, UC Press',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 93, factualVerification: 97, difficultyBalance: 89, answerDistinction: 94, sourceCitations: 95, composite: 94, grade: 'A' },
    plays: 280,
    correctAttempts: 205,
    incorrectAttempts: 75,
    accuracy: 73,
    createdAt: new Date(Date.now() - 21 * 86400000).toISOString()
  },
  {
    id: 'Q-7004',
    authorId: 'user_1',
    deckId: 'deck_7',
    deckName: 'Art Movements & Architecture',
    category: 'Art',
    topic: 'Renaissance Perspective & Optics',
    text: 'Which Renaissance polymath first formally demonstrated the geometric principles of linear one-point perspective in Florence around 1415?',
    prompt: 'Which Renaissance polymath first formally demonstrated the geometric principles of linear one-point perspective in Florence around 1415?',
    options: [
      { id: 'opt_1', text: 'Filippo Brunelleschi', isCorrect: true },
      { id: 'opt_2', text: 'Leonardo da Vinci', isCorrect: false },
      { id: 'opt_3', text: 'Michelangelo Buonarroti', isCorrect: false },
      { id: 'opt_4', text: 'Sandro Botticelli', isCorrect: false }
    ],
    correctAnswerIndex: 0,
    correctIndex: 0,
    explanation: 'Brunelleschi conducted his famous mirror experiment in front of the Florence Baptistery, proving mathematical convergence of parallel lines at a vanishing point.',
    citation: 'Vasari, Lives of the Most Excellent Painters, Sculptors, and Architects',
    citations: 'Vasari, Lives of the Most Excellent Painters, Sculptors, and Architects',
    difficulty: 'medium',
    status: 'Live',
    qualityScores: { originality: 92, factualVerification: 98, difficultyBalance: 90, answerDistinction: 94, sourceCitations: 95, composite: 94, grade: 'A' },
    plays: 350,
    correctAttempts: 260,
    incorrectAttempts: 90,
    accuracy: 74,
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString()
  },
  {
    id: 'Q-7005',
    authorId: 'user_4',
    deckId: 'deck_7',
    deckName: 'Art Movements & Architecture',
    category: 'Art',
    topic: 'Post-Impressionism & Color Theory',
    text: 'Which systematic technique developed by Georges Seurat involves applying tiny dots of pure, unmixed color that optically blend in the viewer’s eye?',
    prompt: 'Which systematic technique developed by Georges Seurat involves applying tiny dots of pure, unmixed color that optically blend in the viewer’s eye?',
    options: [
      { id: 'opt_1', text: 'Sfumato', isCorrect: false },
      { id: 'opt_2', text: 'Pointillism (Chromoluminarism)', isCorrect: true },
      { id: 'opt_3', text: 'Fauvist impasto', isCorrect: false },
      { id: 'opt_4', text: 'Cubist collage', isCorrect: false }
    ],
    correctAnswerIndex: 1,
    correctIndex: 1,
    explanation: 'Georges Seurat and Paul Signac developed Pointillism (Divisionism), relying on Chevreul\'s law of simultaneous color contrast to create luminous optical mixtures.',
    citation: 'Rewald, Post-Impressionism: From Van Gogh to Gauguin, MoMA',
    citations: 'Rewald, Post-Impressionism: From Van Gogh to Gauguin, MoMA',
    difficulty: 'easy',
    status: 'Live',
    qualityScores: { originality: 89, factualVerification: 99, difficultyBalance: 87, answerDistinction: 95, sourceCitations: 94, composite: 93, grade: 'A' },
    plays: 490,
    correctAttempts: 410,
    incorrectAttempts: 80,
    accuracy: 84,
    createdAt: new Date(Date.now() - 33 * 86400000).toISOString()
  }
];

export const initialBattles = [
  {
    id: 'battle_101',
    challengerId: 'user_2',
    challengerName: 'Abram Mango',
    challengerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    challengerLevel: 12,
    opponentId: 'user_1',
    opponentName: 'Kianna Torff',
    opponentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    opponentLevel: 14,
    deckId: 'deck_1',
    subject: 'AP Physics 1: Mechanics',
    status: 'your_turn',
    stateLabel: 'Your Turn',
    currentRound: 3,
    maxRounds: 5,
    userScore: 2,
    opponentScore: 1,
    timeRemainingSeconds: 15,
    dpReward: 120,
    dpLoss: 40,
    questionIds: ['Q-1001', 'Q-1002', 'Q-1003', 'Q-1004', 'Q-1005'],
    roundHistory: [
      { round: 1, questionId: 'Q-1001', userCorrect: true, opponentCorrect: true },
      { round: 2, questionId: 'Q-1002', userCorrect: true, opponentCorrect: false }
    ],
    createdAt: new Date(Date.now() - 40 * 60000).toISOString()
  },
  {
    id: 'battle_102',
    challengerId: 'user_3',
    challengerName: 'Alfonso Lubin',
    challengerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    challengerLevel: 15,
    opponentId: 'user_1',
    opponentName: 'Kianna Torff',
    opponentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    opponentLevel: 14,
    deckId: 'deck_2',
    subject: 'AP Calculus AB & BC',
    status: 'your_turn',
    stateLabel: 'Action Required',
    currentRound: 4,
    maxRounds: 5,
    userScore: 3,
    opponentScore: 3,
    timeRemainingSeconds: 15,
    dpReward: 140,
    dpLoss: 45,
    questionIds: ['Q-2001', 'Q-2002', 'Q-2003', 'Q-2004', 'Q-2005'],
    roundHistory: [
      { round: 1, questionId: 'Q-2001', userCorrect: true, opponentCorrect: true },
      { round: 2, questionId: 'Q-2002', userCorrect: true, opponentCorrect: true },
      { round: 3, questionId: 'Q-2003', userCorrect: true, opponentCorrect: true }
    ],
    createdAt: new Date(Date.now() - 90 * 60000).toISOString()
  },
  {
    id: 'battle_103',
    challengerId: 'user_4',
    challengerName: 'Maren Gouse',
    challengerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    challengerLevel: 9,
    opponentId: 'user_1',
    opponentName: 'Kianna Torff',
    opponentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    opponentLevel: 14,
    deckId: 'deck_4',
    subject: 'Molecular Biology & Genetics',
    status: 'your_turn',
    stateLabel: 'Match Point Risk',
    currentRound: 1,
    maxRounds: 5,
    userScore: 0,
    opponentScore: 0,
    timeRemainingSeconds: 15,
    dpReward: 100,
    dpLoss: 30,
    questionIds: ['Q-4001', 'Q-4002', 'Q-4003', 'Q-4004', 'Q-4005'],
    roundHistory: [],
    createdAt: new Date(Date.now() - 15 * 60000).toISOString()
  },
  {
    id: 'battle_104',
    challengerId: 'user_8',
    challengerName: 'Nadia Okonjo',
    challengerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    challengerLevel: 16,
    opponentId: 'user_1',
    opponentName: 'Kianna Torff',
    opponentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    opponentLevel: 14,
    deckId: 'deck_3',
    subject: 'AP Chemistry',
    status: 'your_turn',
    stateLabel: 'Tie-breaker Active',
    currentRound: 5,
    maxRounds: 5,
    userScore: 4,
    opponentScore: 4,
    timeRemainingSeconds: 15,
    dpReward: 160,
    dpLoss: 50,
    questionIds: ['Q-3001', 'Q-3002', 'Q-3003', 'Q-3004', 'Q-3005'],
    roundHistory: [
      { round: 1, questionId: 'Q-3001', userCorrect: true, opponentCorrect: true },
      { round: 2, questionId: 'Q-3002', userCorrect: true, opponentCorrect: true },
      { round: 3, questionId: 'Q-3003', userCorrect: true, opponentCorrect: true },
      { round: 4, questionId: 'Q-3004', userCorrect: true, opponentCorrect: true }
    ],
    createdAt: new Date(Date.now() - 120 * 60000).toISOString()
  }
];

export const initialIncomingInvites = [
  {
    id: 'invite_201',
    challengerId: 'user_7',
    challengerName: 'Lucas Meyer',
    challengerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    challengerLevel: 13,
    subject: 'AP Chemistry',
    deckId: 'deck_3',
    timeSent: '10m ago'
  },
  {
    id: 'invite_202',
    challengerId: 'user_6',
    challengerName: 'Elena V.',
    challengerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    challengerLevel: 11,
    subject: 'Thermodynamics & Kinetics',
    deckId: 'deck_3',
    timeSent: '45m ago'
  }
];

export const initialBattleLogs = [
  {
    id: 'log_301',
    opponentId: 'user_5',
    opponentName: 'James C.',
    opponentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    subject: 'AP Physics sudden death',
    date: '12m ago',
    finalScore: '5 - 3',
    result: 'W',
    dpChange: 28,
    roundsWon: 5,
    accuracy: 88
  },
  {
    id: 'log_302',
    opponentId: 'user_6',
    opponentName: 'Elena V.',
    opponentAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    subject: 'Chemical Equilibrium speed round',
    date: '1d ago',
    finalScore: '4 - 5',
    result: 'L',
    dpChange: -15,
    roundsWon: 4,
    accuracy: 80
  }
];

export const initialFriendRequests = [
  {
    id: 'freq_1',
    senderId: 'user_4',
    name: 'Maren Gouse',
    senderName: 'Maren Gouse',
    handle: '@maren_g',
    username: 'maren_g',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    level: 9,
    senderLevel: 9,
    rank: 'Veteran Scholar',
    tier: 'VETERAN SCHOLAR',
    dp: 2420,
    message: 'Wants to connect after your recent AP Biology duel.',
    senderBio: 'Wants to connect after your recent AP Biology duel.',
    timeAgo: '2h ago'
  },
  {
    id: 'freq_2',
    senderId: 'user_9',
    name: 'Marcus Vance',
    senderName: 'Marcus Vance',
    handle: '@marcus_v',
    username: 'marcus_v',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    level: 10,
    senderLevel: 10,
    rank: 'Elite Cadet',
    tier: 'ELITE CADET',
    dp: 2480,
    message: 'Invited you to join their CS & Algorithm study guild.',
    senderBio: 'Invited you to join their CS & Algorithm study guild.',
    timeAgo: '4h ago'
  }
];

export const initialFriends = [
  {
    id: 'user_2',
    name: 'Abram Mango',
    handle: '@abram_m',
    username: 'abram_m',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    level: 12,
    onlineStatus: 'online',
    subject: 'AP Physics',
    relationshipTag: 'Rival',
    rank: 'Master Duelist',
    tier: 'MASTER DUELIST',
    dp: 2780,
    streak: 5,
    winRate: '75%',
    difficulty: 'medium',
    personality: 'Fast Strategist'
  },
  {
    id: 'user_3',
    name: 'Alfonso Lubin',
    handle: '@alfonso_l',
    username: 'alfonso_l',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    level: 15,
    onlineStatus: 'online',
    subject: 'AP Calculus',
    relationshipTag: 'Guild',
    rank: 'Master Duelist',
    tier: 'MASTER DUELIST',
    dp: 2690,
    streak: 4,
    winRate: '75%',
    difficulty: 'hard',
    personality: 'Precise Analyst'
  },
  {
    id: 'user_8',
    name: 'Nadia Okonjo',
    handle: '@nadia_o',
    username: 'nadia_o',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    level: 16,
    onlineStatus: 'online',
    subject: 'Genetics & Biotech',
    relationshipTag: 'Co-author',
    rank: 'Apex Master',
    tier: 'APEX MASTER',
    dp: 2810,
    streak: 9,
    winRate: '82%',
    difficulty: 'hard',
    personality: 'Tactical Scholar'
  }
];

export const initialNotifications = [
  {
    id: 'notif_1',
    title: 'New Duel Challenge!',
    message: 'Alfonso Lubin challenged you in AP Calculus AB & BC.',
    time: '5m ago',
    read: false,
    type: 'battle',
    link: '/battles'
  },
  {
    id: 'notif_2',
    title: 'Question Approved (+40 DP)',
    message: 'Your question "Rotational Inertia & Conservation" was peer-approved.',
    time: '2h ago',
    read: false,
    type: 'reward',
    link: '/questions'
  },
  {
    id: 'notif_3',
    title: 'Daily Lightning Arena Open',
    message: 'Double DP active in STEM arenas for the next 5 hours.',
    time: '4h ago',
    read: true,
    type: 'event',
    link: '/'
  }
];

export const initialActivities = [
  {
    id: 'act_1',
    title: 'Match Victory vs James C.',
    text: 'Won 5-round battle in AP Physics (+28 DP).',
    time: '12m ago',
    dp: 28,
    type: 'battle'
  },
  {
    id: 'act_2',
    title: 'Question Approved',
    text: '"Rotational Inertia & Conservation" verified by Peer Council (+40 DP).',
    time: '2h ago',
    dp: 40,
    type: 'question'
  },
  {
    id: 'act_3',
    title: 'Daily Streak Maintained',
    text: 'Day 7 streak completed! Multiplier boosted to 1.35x.',
    time: '5h ago',
    dp: 15,
    type: 'streak'
  },
  {
    id: 'act_4',
    title: 'Deck Practice Completed',
    text: 'Completed 5 questions in AP Calculus AB & BC (+50 DP).',
    time: '1d ago',
    dp: 50,
    type: 'practice'
  },
  {
    id: 'act_5',
    title: 'Royalty Payout Received',
    text: '7 scholars answered your questions (+14 DP).',
    time: '1d ago',
    dp: 14,
    type: 'royalty'
  }
];

export const initialDPTransactions = [
  {
    id: 'tx_1',
    amount: 28,
    reason: 'Battle Victory: AP Physics vs James C.',
    time: '12m ago',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString()
  },
  {
    id: 'tx_2',
    amount: 40,
    reason: 'Peer Review Approval: "Rotational Inertia & Conservation"',
    time: '2h ago',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString()
  },
  {
    id: 'tx_3',
    amount: 15,
    reason: '7-Day Streak Bonus',
    time: '5h ago',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString()
  },
  {
    id: 'tx_4',
    amount: 50,
    reason: 'Practice Session: AP Calculus AB & BC (5/5 correct)',
    time: '1d ago',
    createdAt: new Date(Date.now() - 86400000).toISOString()
  },
  {
    id: 'tx_5',
    amount: 14,
    reason: 'Author Royalty Distribution (7 plays)',
    time: '1d ago',
    createdAt: new Date(Date.now() - 90000000).toISOString()
  }
];
